// admin/src/app/common/components/header/header.component.ts
import { Component, OnInit } from '@angular/core'

@Component({
    selector: 'admin-header',
    templateUrl: './header.component.html',
    styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
    constructor() {}

    ngOnInit(): void {}
}

<header class="rd-admin-header py-4 bg-indigo-600 text-white mb-8 sticky top-0 z-50 border-b-2 border-indigo-900">
    <div class="rd-container flex justify-between">
        <a class="flex items-center" routerLink="/">
            <i class="rd-icon flex-none mr-2 text-3xl">change_history</i>
            <span class="text-2xl font-bold">RD Admin</span>
        </a>
    </div>
</header>

// frontend/admin/src/components/common/Header.vue
<template>
	<header class="py-3 bg-blue-700 mb-6 sticky top-0 z-40">
		<div class="centered flex items-center justify-between">
			<div class="xl:hidden">
				<div class="mr-3 flex-none cursor-pointer" @click="toggleOffcanvas">
					<i class="rd-icon text-3xl">menu</i>
				</div>
			</div>
			<router-link :to="{ name: 'admin-main' }" class="font-bold flex items-center">
				<i class="rd-icon flex-none mr-2 text-3xl">change_history</i>
				<span>RDAdmin</span>
			</router-link>
			<div class="flex">
				<div class="flex-none cursor-pointer">
					<i class="rd-icon text-3xl">account_circle</i>
				</div>
			</div>
		</div>
	</header>
</template>

<script>
import { toggleOffcanvas } from '@/reactive/offcanvas';

export default {
	name: 'rd-header',
	setup() {
		return {
			toggleOffcanvas,
		};
	},
};
</script>
