// app/components/common/header.vue
<template>
	<header class="app-header">
		<div class="centered flex items-center justify-between">
			<div>
				<router-link class="text-lg font-bold" to="/">RD App</router-link>
			</div>
			<div class="flex items-center space-x-4">
				<router-link to="/">Main</router-link>
				<router-link to="/about">About</router-link>
				<router-link to="/test">Test</router-link>
				<router-link to="/log">Log</router-link>
			</div>
		</div>
	</header>
</template>

<style lang="scss">
.app-header {
	@apply mb-6 py-5 sticky bg-blue-600 text-white;
}
</style>

// admin/src/app/common/components/header/header.component.ts
import { Component, OnInit } from '@angular/core'

@Component({
    selector: 'admin-header',
    templateUrl: './header.component.html',
    styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
    constructor() {}

    ngOnInit(): void {}
}

<header class="rd-admin-header py-4 bg-indigo-600 text-white mb-8 sticky top-0 z-50 border-b-2 border-indigo-900">
    <div class="rd-container flex justify-between">
        <a class="flex items-center" routerLink="/">
            <i class="rd-icon flex-none mr-2 text-3xl">change_history</i>
            <span class="text-2xl font-bold">RD Admin</span>
        </a>
    </div>
</header>
