// frontend/admin/src/components/pages/PageForm.vue
<template>
	<form
		@submit.prevent="formSubmit($event)"
		:class="{ 'opacity-50 pointer-events-none': loading }"
		class="grid grid-cols-1 gap-6 xl:grid-cols-2"
	>
		<label>
			<div class="mb-3 text-gray-400 font-bold text-14px">Путь (url - /example)</div>
			<input
				type="text"
				@input="onPathInput($event)"
				:value="formFields.path"
				class="rd-form-control"
				required
				ref="firstInputRef"
			/>
		</label>
		<label>
			<div class="mb-3 text-gray-400 font-bold text-14px">Заголовок страницы - (H1)</div>
			<input type="text" v-model="formFields.title" class="rd-form-control" required />
		</label>
		<label>
			<div class="mb-3 text-gray-400 font-bold text-14px">Редирект</div>
			<input type="text" v-model="formFields.redirect" class="rd-form-control" />
		</label>
		<label>
			<div class="mb-3 text-gray-400 font-bold text-14px">Файл шаблона (BasePage - по умолчанию)</div>
			<input type="text" v-model="formFields.template_filename" class="rd-form-control" />
		</label>
		<label class="xl:col-span-2">
			<div class="mb-3 text-gray-400 font-bold text-14px">{{ 'Данные JSON {"some": "value"}' }}</div>
			<textarea v-model="formFields.json_data" rows="6" class="rd-form-control resize-y"></textarea>
		</label>
		<label>
			<div class="mb-3 text-gray-400 font-bold text-14px">{{ 'Title страницы (<title></title>)' }}</div>
			<input type="text" v-model="formFields.page_title" class="rd-form-control" />
		</label>
		<label>
			<div class="mb-3 text-gray-400 font-bold text-14px">
				{{ 'Description страницы (&#60;meta name="description" /&#62;)' }}
			</div>
			<input type="text" v-model="formFields.page_description" class="rd-form-control" />
		</label>
		<label>
			<div class="mb-3 text-gray-400 font-bold text-14px">
				{{ 'Скрипты &#60;script&#62;...&#60;/script&#62;' }}
			</div>
			<textarea v-model="formFields.scripts" rows="6" class="rd-form-control resize-y"></textarea>
		</label>
		<label>
			<div class="mb-3 text-gray-400 font-bold text-14px">
				{{ 'Стили &#60;style&#62;...&#60;style&#62; или &#60;link href="..." /&#62;' }}
			</div>
			<textarea v-model="formFields.styles" rows="6" class="rd-form-control resize-y"></textarea>
		</label>
		<div class="select-none">
			<label class="inline-flex items-center">
				<input type="checkbox" v-model="formFields.hidden" class="flex-none mr-2 w-6 h-5" />
				<div>Скрыть (Не будет и отображаться на сайте)</div>
			</label>
		</div>
		<div class="fixed z-20 inset-x-0 bottom-0 py-4 flex justify-center shadow-md bg-gray-700">
			<button type="submit" class="rd-button rd-button--success" :class="{ 'rd-button--loading': loading }">
				<span>{{ actionType === 'edit' ? 'Редактировать' : 'Создать' }}</span>
			</button>
		</div>
	</form>
</template>

<script>
import { onMounted, ref } from 'vue';

export default {
	props: {
		formFields: {
			type: Object,
			required: true,
		},
		actionType: {
			type: String,
			default: 'create',
			required: true,
		},
		loading: {
			type: Boolean,
			default: false,
			required: true,
		},
	},
	setup({ formFields, actionType, loading }, context) {
		const firstInputRef = ref(null);

		if (actionType === 'edit' && formFields.json_data && typeof formFields.json_data === 'object') {
			formFields.json_data = JSON.stringify(formFields.json_data);
		}

		const urlParser = (string) => {
			let finalValue = string.toLowerCase();
			if (finalValue.startsWith('/')) {
				return finalValue;
			}
			return `/${finalValue}`;
		};

		const onPathInput = (event) => {
			formFields.path = urlParser(event.target.value);
		};

		const formSubmit = (event) => {
			context.emit('emitSubmit', formFields);
		};

		onMounted(() => {
			firstInputRef.value.focus();
		});

		return {
			loading,
			formSubmit,
			firstInputRef,
			onPathInput,
		};
	},
};
</script>

// admin/src/app/modules/pages/components/page-form/page-form.component.ts
import { Component, OnInit } from '@angular/core'
import { ActivatedRoute, Data } from '@angular/router'
import { Observable } from 'rxjs'

@Component({
    selector: 'admin-page-form',
    templateUrl: './page-form.component.html',
    styleUrls: ['./page-form.component.scss'],
})
export class PageFormComponent implements OnInit {
    public routeData$?: Observable<Data>

    constructor(private readonly route: ActivatedRoute) {}

    ngOnInit(): void {
        this.routeData$ = this.route.data
    }

    public formSubmit(event: Event) {
        event.preventDefault()
    }
}

<form (submit)="formSubmit($event)" class="pb-20">
    <div class="lg:flex lg:flex-wrap">
        <label class="mb-5 block lg:w-1/2 lg:pr-3">
            <div class="mb-2 font-medium">Путь страницы (url)</div>
            <input type="text" autofocus class="rd-form-field" />
        </label>
        <label class="mb-5 block lg:w-1/2 lg:pl-3">
            <div class="mb-2 font-medium">Заголовок страницы (h1)</div>
            <input type="text" autofocus class="rd-form-field" />
        </label>
        <label class="mb-5 block w-full">
            <div class="mb-2 font-medium">Контент страницы</div>
            <textarea class="rd-form-field" rows="8"></textarea>
        </label>
        <label class="mb-5 block lg:w-1/2 lg:pr-3">
            <div class="mb-2 font-medium">Редирект</div>
            <input type="text" autofocus class="rd-form-field" />
        </label>
        <label class="mb-5 block lg:w-1/2 lg:pl-3">
            <div class="mb-2 font-medium">Файл шаблона (layout)</div>
            <input type="text" autofocus class="rd-form-field" />
        </label>
        <label class="mb-5 block lg:w-1/2 lg:pr-3">
            <div class="mb-2 font-medium">Title страницы</div>
            <textarea class="rd-form-field" rows="5"></textarea>
        </label>
        <label class="mb-5 block lg:w-1/2 lg:pl-3">
            <div class="mb-2 font-medium">Description страницы</div>
            <textarea class="rd-form-field" rows="5"></textarea>
        </label>
        <label class="mb-5 block lg:w-1/2 lg:pr-3">
            <div class="mb-2 font-medium">Скрипты страницы (script)</div>
            <textarea class="rd-form-field" rows="5"></textarea>
        </label>
        <label class="mb-5 block lg:w-1/2 lg:pl-3">
            <div class="mb-2 font-medium">Стили страницы (style, link)</div>
            <textarea class="rd-form-field" rows="5"></textarea>
        </label>
        <div class="w-full mb-6">
            <div class="inline-flex items-center cursor-pointer">
                <i class="rd-icon text-red-500 text-[28px] mr-2">visibility_off</i>
                <div class="font-medium">Скрыть страницу</div>
            </div>
        </div>
    </div>
    <div class="fixed left-0 right-0 bottom-0 flex justify-center bg-gray-300 py-3 z-50">
        <button class="rd-button rd-button--success">
            {{ (routeData$ | async)?.actionType === 'create' ? 'Создать' : 'Редактировать' }}
        </button>
    </div>
</form>
